version: '3.3'

services:
  web:
    build:
      context: ../
      dockerfile: ot_server/Dockerfile
    container_name: ot_server
    network_mode: host
#    ports:
#      - '8000:8000/tcp'
#      - '8000:8000/udp'
    restart: always