version: '3.3'

services:
  web:
    build:
      context: ../
      dockerfile: ot_server/Dockerfile
    container_name: ot_server
    network_mode: host
    #    ports:
    #      - "8000:8000"
    volumes:
      - ./rsa_keys:/service/ot_server/build/rsa_keys
      - ./conf:/service/ot_server/build/conf
    command:
      - argsFromConf=true
      - confFile=conf/ot_server.ini
    restart: always
    depends_on:
      - db

  db:
    image: redis:6.2.6-alpine
    container_name: redis
    network_mode: host
    #    ports:
    #      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server /data/redis.conf
    restart: always