version: '3.3'

services:
  web:
    build:
      context: ../
      dockerfile: ot_client/Dockerfile
    container_name: ot_client
    network_mode: host
    #    ports:
    #      - "8001:8001"
    volumes:
      - ./conf:/service/ot_client/build/conf
    command:
      - argsFromConf=true
      - confFile=conf/ot_client.ini
    restart: always