version: '3.3'

services:
  web:
    build:
      context: ../
      dockerfile: ot_client/Dockerfile
    container_name: ot_client
    network_mode: host
    #    ports:
    #      - '8001:8001/tcp'
    #      - '8001:8001/udp'
    volumes:
      - ./conf:/service/ot_server/build/conf
    command:
      - argsFromConf=true
      - confFile=conf/ot_server.ini
    restart: always