version: '3.3'

services:
  web:
    build:
      context: ../
      dockerfile: ot_client/Dockerfile
    container_name: ot_client
    ports:
      - '8001:8001/tcp'
      - '8001:8001/udp'
    restart: always